### ISSUE TITLE
Retorno da função load_compromiser

### ISSUE THREAD

**Issue by akemi-adam** [Paulo-Douglas/SigTask#64]
<h2 align="center">Retorno da função load_compromiser</h2>

<h2 align="center">Descrição</h2>

Estou analisando o código para a avaliação de Flavius e ao ver o arquivo <a href="https://github.com/Paulo-Douglas/SigTask/blob/main/Compromissos/CompromissosModel.c">CompromissosModel.c</a> (branch main) percebi que o operador ternário sempre retorna o valor da condição verdadeira (Já quer a condição do operador é a constante TRUE). Poderia ser o caso de remover ele e deixar a função retornar o valor de `found`.

```c
int load_compromiser() {
// code ...
return TRUE ? found : FALSE;
}
```

Falando só pra contribuir, não estou levando em conta isso na avaliação. Projeto muito bom, parabéns.

**Comment by andrewszada** [comment]
@akemi-adam, grato pela contribuição, Mosiah!

**Comment by anderson-cruz13** [comment]
obrigado pela observação
